[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[headers]]
for = "*.js"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "*.jsx"
[headers.values]
Content-Type = "application/javascript"